name: Deploy HTML to S3

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload HTML files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          source_dir: .  # Uploads all files from the root directory
          destination_bucket: ${{ secrets.AWS_S3_BUCKET }}
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
